apiVersion: v1
kind: Pod
metadata:
  name: deploi-agent
  namespace: kube-system
  labels:
    name: deploi
spec:
  containers:
  - name: deploi-agent
    image: registry.cargo.one:5000/deploi-agent:latest
    imagePullPolicy: Never
    args: ["-host", "192.168.200.187:8000", "-environment", "mike", "-namespaces", "test" ]
