apiVersion: v1
kind: Pod
metadata:
  name: deploi-agent
  namespace: kube-system
  labels:
    app: deploi-agent
spec:
  containers:
  - name: deploi-agent
    image: registry.cargo.one:5000/deploi-agent:latest
    args: ["-host", "deploid.cargo.one:3375", "-environment", "staging", "-namespaces", "default" ]
